services:
  web: &web-container
    build:
      dockerfile: ./infra/web/Dockerfile
      context: ./
      target: base
    restart: unless-stopped
    depends_on:
      - "redis"
    volumes:
      - .:/var/www/html
    env_file: .env
    ports:
      - "3010:8080"

  queue:
    <<: *web-container
    command: nice -n 10 php craft queue/listen --verbose
    ports: []

  redis:
    image: redis:8-alpine
    command: redis-server --requirepass redispw
    restart: always

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3306"

volumes:
  db_data:
