# A docker-compose file that contains services to be built and pushed as part of a CI deploy process
services:
  # The php/nginx service that is built and pushed to GitHub Container Registry and serves as the basis for our php container on remote environments
  web:
    image: "${GHCR_REGISTRY:-ghcr.io}/${GHCR_REPOSITORY:-web}:${BRANCH:-dev}"
    build:
      dockerfile: ./infra/web/Dockerfile
      context: ./
      target: "${DOCKER_TARGET_WEB:-app}"
