# A docker compose file that is used by the CI deploy process to build production images.
services:
  web:
    image: "${GHCR_REGISTRY:-ghcr.io}/${GHCR_REPOSITORY:-web}:${BRANCH:-dev}"
    build:
      dockerfile: ./infra/web/Dockerfile
      context: ./
      target: "${DOCKER_TARGET_WEB:-app}"
