dateModified: 1754868785
email:
  fromEmail: eli@happycog.com
  fromName: 'Craft Docker Deployments Test Site'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    2ff7fa9c-735e-452e-8af3-7bcfa8e0720d: 'Craft Docker Deployments Test Site' # Craft Docker Deployments Test Site
    f8531777-17d2-47b6-8a03-5f97a1ac2058: 'Craft Docker Deployments Test Site' # Craft Docker Deployments Test Site
plugins:
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: 'Craft Docker Deployments Test Site'
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
