name: Deploy to Staging

concurrency:
  group: staging
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - staging

# These permissions are needed to interact with GitHub Container Registry.
permissions:
  packages: write
  contents: read

jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: staging
      domain: staging.hamiltoncompany.com
      basic-auth: "hamilton:hamiltonprivate"
      slack_channel_id: 'C049XB4PYFJ' # Or from a secret: ${{ secrets.SLACK_CHANNEL_ID_PROD }}
    secrets: inherit
