name: Deploy to Production

concurrency:
  group: production
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - main

# These permissions are needed to push to GitHub Container Registry.
permissions:
  packages: write
  contents: read

jobs:
  call-deployment:
    uses: ./.github/workflows/deployment.yml
    with:
      environment: production
      domain: www.craft-deployment-test.com
      basic-auth:
      slack_webhook_url: '' # Or from a secret: ${{ secrets.SLACK_CHANNEL_ID }}
      slack_channel_id: '' # Or from a secret: ${{ secrets.SLACK_WEBHOOK_URL }}
    secrets: inherit
